name: CI

on:
  push:
    paths:
    - 'ffq/**'
    - 'tests/**'

jobs:
  check-code:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install 3.9
      - name: Install dependencies
        run: uv sync
      - name: Check code quality
        run: make check
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.9', '3.10', '3.11', '3.12']
    name: Test on Python ${{ matrix.python }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install ${{ matrix.python }}
      - name: Install dependencies
        run: uv sync --python ${{ matrix.python }}
      - name: Run tests
        run: uv run coverage run -m pytest -ra -v tests && uv run coverage report --omit=main.py,tests*
